@startuml
package huang.wen.manage{
    +class Main {
       {static} + void main(String args[])
    }
   +class DBUtil{
        +Connection getConnection()
        +void close(PreparedStatement pstmt)
        +void close(Connection conn)
        +void close(ResultSet rs)
    }
    +class Administrator {
        String name_administrator
        String gender_administrator
        String account_administrator
        -JFrame Administrator
        -JPanel panel1
        -JSplitPane splitPane1
        -JSplitPane splitPane2
        -JLabel label_name
        -JSplitPane splitPane3
        -JLabel label_gender
        -JSplitPane splitPane4
        -JButton button_addCar
        -JSplitPane splitPane5
        -JButton button_reviseCar
        -JSplitPane splitPane6
        -JButton button_findCar
        -JSplitPane splitPane7
        -JButton button_removeCar
        -JSplitPane splitPane8
        -JLabel label1
        -JSplitPane splitPane9
        -JButton button_turnover
        -JSplitPane splitPane10
        -JButton button_exportInformation
        -JSplitPane splitPane11
        -JButton button_exitSystem
        -JTextField textField1
        -JTabbedPane Menu
        -JScrollPane scrollPane1
        -JTable table_garage
        -JScrollPane scrollPane2
        -JTable table_users
        +Administrator(String account)
        -void initComponents()
        void RefreshUserInformation(ResourceBundle bundle)
        void DisplayUserInformation(Connection conn)
        void DisplayVehicles(Connection conn)
    }
    class Users_infor{
        -String name
        -String gender
        -String account
        -String is_rent
        -float balance
        +Users_infor(String name, String gender, String account, String is_rent, float balance)
        +String getName()
        +String getGender()
        +void setGender(String gender)
        +String getAccount()
        +void setAccount(String account)
        +String getIs_rent()
        +void setIs_rent(String is_rent)
        +float getBalance()
        +void setBalance(float balance)
        +void setName(String name)
    }
    +class VehicleFactory {
        MotoVehicle getVehicleByType(String type)
    }
    +class Turnover {
        String account_administration
        -JFrame Turnover
        -JPanel panel1
        -JSplitPane splitPane1
        -JScrollPane scrollPane1
        -JTable table1
        -JSplitPane splitPane2
        -JSplitPane splitPane3
        -JButton button1
        -JButton button2
        -JTextField textField1;
        +Turnover(String account)
        -void initComponents()
        -void refresh()
    }
    +class User {
        String name_user
        String gender_user
        String account_user
        float balance_user
        String is_rent_user
        float turnover
        +User(String account)
        -void initComponents()
        void find_Cars(Connection conn,int pattern)
        void find_Buses(Connection conn,int pattern)
        void find_Trucks(Connection conn,int pattern)
        void RefreshUserInformation(ResourceBundle bundle)
        - JFrame Jframe_user;
        - JLabel label1;
        - JPanel panel1;
        - JTabbedPane menu;
        - JScrollPane scrollPane1;
        - JTable car;
        - JScrollPane scrollPane3;
        - JTable bus;
        - JScrollPane scrollPane4;
        - JTable truck;
        - JScrollPane scrollPane5;
        - JPanel panel2;
        - JLabel label3;
        - JSplitPane splitPane3;
        - JSplitPane splitPane2;
        - JSplitPane splitPane6;
        - JLabel label_greetings;
        - JLabel label5;
        - JSplitPane splitPane13;
        - JLabel label_name;
        - JSplitPane splitPane14;
        - JLabel label_gender;
        - JSplitPane splitPane15;
        - JLabel label_account;
        - JSplitPane splitPane16;
        - JLabel label_accountBalance;
        - JPanel vSpacer1;
        - JSplitPane splitPane4;
        - JSplitPane splitPane5;
        - JButton Button_rentCar;
        - JButton Button_returnVehicle;
        - JSplitPane splitPane1;
        - JButton Button_viewAllVehicles;
        - JSplitPane splitPane7;
        - JButton Button_viewAvailableVehicles;
        - JSplitPane splitPane8;
        - JButton Button_rentalSituation;
        - JSplitPane splitPane9;
        - JLabel label4;
        - JSplitPane splitPane10;
        - JButton Button_accountRecharge;
        - JSplitPane splitPane11;
        - JButton Button_changePassword;
        - JSplitPane splitPane12;
        - JButton Button_signOut;
        -JSplitPane splitPane17;
        -JButton button1;
        -JLabel label2
    }
    class MyTableModel extends DefaultTableModel{
        public boolean isCellEditable(int row, int column)
        public MyTableModel(Vector data,Vector columns)
    }
}


package huang.wen.other{
    +class ChangePassword {
        String user_account
        + ChangePassword(Connection conn ,String account)
        - void initComponents()
        - JFrame ChangePassword
        - JPanel panel1
        - JSplitPane splitPane7
        - JSplitPane splitPane8
        - JSplitPane splitPane9
        - JLabel label3
        - JPasswordField passwordField3
        - JSplitPane splitPane1
        - JLabel label1
        - JPasswordField passwordField1
        - JSplitPane splitPane2
        - JSplitPane splitPane3
        - JLabel label2
        - JPasswordField passwordField2
        - JSplitPane splitPane4
        - JButton button1
        - JButton button2
    }


    +class Register extends JFrame {
        +Register()
        - void initComponents()
        - JButton returnButton
        - JPanel panel1
        - JSplitPane splitPane4
        - JSplitPane splitPane5
        - JLabel label7
        - JTextField textField2
        - JSplitPane splitPane6
        - JCheckBox checkBox1
        - JButton registerButton
        - JSplitPane splitPane1
        - JSplitPane splitPane2
        - JLabel label4
        - JLabel label5
        - JSplitPane splitPane3
        - JTextField textField1
        - JPasswordField passwordField1
        - JLabel label6
        - JSplitPane splitPane7
        - JSplitPane splitPane8
        - JLabel label8
        - JTextField textField3
    }
    +class Welcome extends JFrame {
        +Welcome()
        - void initComponents()
        - JFrame frame1
        - JPanel panel1
        - JSplitPane splitPane3
        - JSplitPane splitPane4
        - JLabel label1
        - JLabel label2
        - JSplitPane splitPane5
        - JTextField inputAccount
        - JPasswordField inputPassword
        - JSplitPane splitPane1
        - JCheckBox checkBox1
        - JSplitPane splitPane2
        - JButton loginButton
        - JButton registerButton
        - JLabel title
        - JSplitPane splitPane6
        - JLabel label3
        - JButton moreButton
    }
}

package huang.wen.cars{
    +abstract class MotoVehicle {
        - String vehicleId
        - String brand
        - float rent
        + String flag
        + String date
        + MotoVehicle(String vehicleId, String brand, float rent, String flag,String date)
        + MotoVehicle()
        + String getFlag()
        + void setFlag(String flag)
        + String getPlateNumber()
        + void setPlateNumber(String plateNumber)
        + String getBrand()
        + void setBrand(String brand)
        + float getPerRent()
        + void setPerRent(float rent)
        + void AddProcess(JFrame Administrator)
        + String getDate()
        + void setDate(String date)
        + {abstract} void calRent(int days)
        + void leaseOutFlow()
    }

    +class Car extends MotoVehicle {
        String type
        + Car(String flag, String vehicleId, String brand, String type, float rent,String date)
        + Car()
        + String getType()
        + void setType(String type)
        + void AddProcess(JFrame Administrator)
        + void calRent(int days)
    }

    +class Bus extends MotoVehicle {
        - int seat
        + Bus(String flag,String vehicleId, String brand, int seat,float rent,String date)
        + Bus()
        + int getSeat()
        + void setSeat(int seat)
        + void AddProcess(JFrame Administrator)
        + void calRent(int days)
    }

   +class Truck extends MotoVehicle {
        float tonnage
        + Truck(String flag,String vehicleId, String brand, float tonnage,float rent,String date)
        + Truck()
        + double getTon()
        + void setTon(float ton)
        + void AddProcess(JFrame Administrator)
        + void calRent(int days)
    }

}

@enduml